#YAML for compiling c sharp project

trigger:
 - Master

pool:
  name: Default

variables:
  buildConfiguration: 'Release'

steps:
  - task: DotNetCoreCLI@2
    displayName: 'dotnet build --configuration $(buildConfiguration)'
    inputs:
      command: build
      projects: '**/*.csproj'
      arguments: '--configuration $(buildConfiguration)'
  
  - task: PowerShell@2
    condition: failed()
    inputs:
      script: |
        New-Item "$(Build.SourcesDirectory)/BuildLog.txt"
    
  
  - task: DotNetCoreCLI@2
    displayName: 'dotnet publish'
    inputs:
      command: publish
      publishWebProjects: false
      projects: 'Project/GetSystemVariables.csproj'
      arguments: '--configuration $(buildConfiguration) --output $(Build.StagingDirectory)'
      zipAfterPublish: true

  - task: PublishBuildArtifacts@1

  - task: cmdLine@2
    inputs:
      script: |
        "$(Build.SourcesDirectory)\Project\bin\Release\net7.0\GetSystemVariables.exe"
