#YAML for compiling c sharp project

trigger:
 - Master

pool:
  name: Default

variables:
  buildConfiguration: 'Release'

steps:
  - task: DotNetCoreCLI@2
    displayName: 'dotnet build --configuration $(buildConfiguration)'
    inputs:
      command: build
      projects: '**/*.csproj'
      arguements: '--configuration $(buildConfiguration)'
  
  

