#YAML for compiling c sharp project

trigger:
 - Master

pool:
  name: Default

variables:
  buildConfiguration: 'Release'

steps:
  - task: DotNetCoreCLI@2
    displayName: 'dotnet build --configuration $(buildConfiguration)'
    inputs:
      command: build
      projects: '**/*.csproj'
      arguments: '--configuration $(buildConfiguration)'
  
  - task: DotNetCoreCLI@2
    displayName: 'dotnet publish'
    inputs:
      command: publish
      publishWebProjects: false
      projects: 'Project/GetSystemVariables.csproj'
      arguments: '--configuration $(buildConfiguration) --output $(Build.StagingDirectory)'
      zipAfterPublish: true

  - task: PublishBuildArtifacts@1

  - task: cmdLine@2
    inputs:
      script: |
        "C:\Users\MohammedAbubakkarSid\Downloads\BuiltProject\GetSystemVariables.exe"
        PATH
  
  - task: cmdLine@2
    inputs: 
      script: |
        "C:\Users\MohammedAbubakkarSid\Downloads\BuiltProject\GetSystemVariables.exe"
        OS
  
  - task: cmdLine@2
    inputs:
      script: |
        "C:\Users\MohammedAbubakkarSid\Downloads\BuiltProject\GetSystemVariables.exe"
        ComSpec
  
  - task: cmdLine@2
    inputs:
      script: |
        "C:\Users\MohammedAbubakkarSid\Downloads\BuiltProject\GetSystemVariables.exe"
        DriverData

  - task: cmdLine@2
    inputs: 
      script: |
        "C:\Users\MohammedAbubakkarSid\Downloads\BuiltProject\GetSystemVariables.exe"
        NUMBER_OF_PROCESSORS
  
  - task: cmdLine@2
    inputs: 
      script: |
        "C:\Users\MohammedAbubakkarSid\Downloads\BuiltProject\GetSystemVariables.exe"
        USERNAME
