#YAML for compiling c sharp project

trigger:
 - Master

pool:
  name: Default

variables:
  buildConfiguration: 'Release'

steps:
  - task: DotNetCoreCLI@2
    displayName: 'dotnet build --configuration $(buildConfiguration)'
    inputs:
      command: build
      projects: '**/*.csproj'
      arguements: '--configuration $(buildConfiguration)'
  
  - task: DotNetCoreCLI@2
    displayName: 'dotnet publish'
    inputs:
      command: publish
      publishWebProjects: false
      projects: 'Project/GetSystemVariables.csproj'
      arguements: '--configuration $(buildConfiguration) --output $(Build.StagingDirectory)'
      zipAfterPublish: true
  
  - task: PublishBuildArtifacts@1
    displayName: publish

